// Generated by scripts/sync-open-formats.mjs from scripts/open-formats.mjs. Do not edit directly.
package com.yaochn.auroraprimeoffice;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

final class OpenFormats {
  /** Picker filter and fallback accept list; mirrors the intent filters in the manifest. */
  static final String[] MIME_TYPES = {
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-excel.sheet.macroEnabled.12",
    "application/vnd.ms-excel",
    "text/csv",
    "text/tab-separated-values",
    "application/x-jmp-data-table",
    "application/vnd.sas.jmp",
    "application/x-jmp",
    "application/vnd.ms-visio.drawing",
    "application/vnd.ms-visio.drawing.main+xml",
    "application/vnd.visio",
    "application/x-visio",
    "application/vnd.jgraph.mxfile",
    "application/x-drawio",
    "application/pdf",
    "application/ofd",
    "application/epub+zip",
    "text/markdown",
    "text/x-markdown",
    "application/x-markdown",
    "image/png",
    "image/jpeg",
    "image/webp",
    "image/emf",
    "application/emf",
    "application/x-emf",
    "image/wmf",
    "application/wmf",
    "application/x-wmf",
    "application/x-msmetafile",
    "image/gif",
    "image/bmp",
    "image/x-bmp",
    "image/x-ms-bmp",
    "image/svg+xml",
    "image/tiff",
    "image/tiff-fx",
    "image/heic",
    "image/heif",
    "image/heic-sequence",
    "image/heif-sequence",
    "text/plain",
    "text/x-java-source",
    "text/javascript",
    "application/javascript",
    "application/json",
    "text/html",
    "text/css",
    "text/x-python",
    "text/x-shellscript",
    "application/yaml",
    "text/yaml",
    "application/xml",
    "text/xml",
    "application/octet-stream",
  };

  private static final Map<String, String> SAVE_MIME_TYPES = new HashMap<>();

  static {
    SAVE_MIME_TYPES.put(
        "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    SAVE_MIME_TYPES.put("doc", "application/msword");
    SAVE_MIME_TYPES.put("dot", "application/msword");
    SAVE_MIME_TYPES.put(
        "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
    SAVE_MIME_TYPES.put("ppt", "application/vnd.ms-powerpoint");
    SAVE_MIME_TYPES.put("pps", "application/vnd.ms-powerpoint");
    SAVE_MIME_TYPES.put("pot", "application/vnd.ms-powerpoint");
    SAVE_MIME_TYPES.put(
        "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    SAVE_MIME_TYPES.put("xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12");
    SAVE_MIME_TYPES.put("xls", "application/vnd.ms-excel");
    SAVE_MIME_TYPES.put("xlt", "application/vnd.ms-excel");
    SAVE_MIME_TYPES.put("csv", "text/csv");
    SAVE_MIME_TYPES.put("tsv", "text/tab-separated-values");
    SAVE_MIME_TYPES.put("jmp", "application/x-jmp-data-table");
    SAVE_MIME_TYPES.put("vsdx", "application/vnd.ms-visio.drawing");
    SAVE_MIME_TYPES.put("vsd", "application/vnd.visio");
    SAVE_MIME_TYPES.put("vss", "application/vnd.visio");
    SAVE_MIME_TYPES.put("vst", "application/vnd.visio");
    SAVE_MIME_TYPES.put("drawio", "application/vnd.jgraph.mxfile");
    SAVE_MIME_TYPES.put("pdf", "application/pdf");
    SAVE_MIME_TYPES.put("ofd", "application/ofd");
    SAVE_MIME_TYPES.put("epub", "application/epub+zip");
    SAVE_MIME_TYPES.put("md", "text/markdown");
    SAVE_MIME_TYPES.put("markdown", "text/markdown");
    SAVE_MIME_TYPES.put("png", "image/png");
    SAVE_MIME_TYPES.put("jpg", "image/jpeg");
    SAVE_MIME_TYPES.put("jpeg", "image/jpeg");
    SAVE_MIME_TYPES.put("webp", "image/webp");
    SAVE_MIME_TYPES.put("emf", "image/emf");
    SAVE_MIME_TYPES.put("wmf", "image/wmf");
    SAVE_MIME_TYPES.put("gif", "image/gif");
    SAVE_MIME_TYPES.put("bmp", "image/bmp");
    SAVE_MIME_TYPES.put("dib", "image/bmp");
    SAVE_MIME_TYPES.put("svg", "image/svg+xml");
    SAVE_MIME_TYPES.put("tif", "image/tiff");
    SAVE_MIME_TYPES.put("tiff", "image/tiff");
    SAVE_MIME_TYPES.put("heic", "image/heic");
    SAVE_MIME_TYPES.put("heif", "image/heic");
    SAVE_MIME_TYPES.put("hif", "image/heic");
    SAVE_MIME_TYPES.put("txt", "text/plain");
    SAVE_MIME_TYPES.put("log", "text/plain");
    SAVE_MIME_TYPES.put("java", "text/plain");
    SAVE_MIME_TYPES.put("js", "text/plain");
    SAVE_MIME_TYPES.put("mjs", "text/plain");
    SAVE_MIME_TYPES.put("cjs", "text/plain");
    SAVE_MIME_TYPES.put("jsx", "text/plain");
    SAVE_MIME_TYPES.put("ts", "text/plain");
    SAVE_MIME_TYPES.put("mts", "text/plain");
    SAVE_MIME_TYPES.put("cts", "text/plain");
    SAVE_MIME_TYPES.put("tsx", "text/plain");
    SAVE_MIME_TYPES.put("json", "text/plain");
    SAVE_MIME_TYPES.put("jsonl", "text/plain");
    SAVE_MIME_TYPES.put("jsonc", "text/plain");
    SAVE_MIME_TYPES.put("html", "text/plain");
    SAVE_MIME_TYPES.put("htm", "text/plain");
    SAVE_MIME_TYPES.put("css", "text/plain");
    SAVE_MIME_TYPES.put("scss", "text/plain");
    SAVE_MIME_TYPES.put("less", "text/plain");
    SAVE_MIME_TYPES.put("vue", "text/plain");
    SAVE_MIME_TYPES.put("py", "text/plain");
    SAVE_MIME_TYPES.put("pyw", "text/plain");
    SAVE_MIME_TYPES.put("rb", "text/plain");
    SAVE_MIME_TYPES.put("sh", "text/plain");
    SAVE_MIME_TYPES.put("bash", "text/plain");
    SAVE_MIME_TYPES.put("zsh", "text/plain");
    SAVE_MIME_TYPES.put("yml", "text/plain");
    SAVE_MIME_TYPES.put("yaml", "text/plain");
    SAVE_MIME_TYPES.put("toml", "text/plain");
    SAVE_MIME_TYPES.put("ini", "text/plain");
    SAVE_MIME_TYPES.put("conf", "text/plain");
    SAVE_MIME_TYPES.put("cfg", "text/plain");
    SAVE_MIME_TYPES.put("properties", "text/plain");
    SAVE_MIME_TYPES.put("env", "text/plain");
    SAVE_MIME_TYPES.put("c", "text/plain");
    SAVE_MIME_TYPES.put("h", "text/plain");
    SAVE_MIME_TYPES.put("cpp", "text/plain");
    SAVE_MIME_TYPES.put("hpp", "text/plain");
    SAVE_MIME_TYPES.put("cc", "text/plain");
    SAVE_MIME_TYPES.put("cxx", "text/plain");
    SAVE_MIME_TYPES.put("cs", "text/plain");
    SAVE_MIME_TYPES.put("go", "text/plain");
    SAVE_MIME_TYPES.put("rs", "text/plain");
    SAVE_MIME_TYPES.put("sql", "text/plain");
    SAVE_MIME_TYPES.put("php", "text/plain");
    SAVE_MIME_TYPES.put("swift", "text/plain");
    SAVE_MIME_TYPES.put("kt", "text/plain");
    SAVE_MIME_TYPES.put("kts", "text/plain");
    SAVE_MIME_TYPES.put("diff", "text/plain");
    SAVE_MIME_TYPES.put("patch", "text/plain");
    SAVE_MIME_TYPES.put("gradle", "text/plain");
    SAVE_MIME_TYPES.put("groovy", "text/plain");
    SAVE_MIME_TYPES.put("dockerfile", "text/plain");
    SAVE_MIME_TYPES.put("makefile", "text/plain");
    SAVE_MIME_TYPES.put("ps1", "text/plain");
    SAVE_MIME_TYPES.put("psm1", "text/plain");
    SAVE_MIME_TYPES.put("bat", "text/plain");
    SAVE_MIME_TYPES.put("cmd", "text/plain");
    SAVE_MIME_TYPES.put("lua", "text/plain");
    SAVE_MIME_TYPES.put("r", "text/plain");
    SAVE_MIME_TYPES.put("pl", "text/plain");
    SAVE_MIME_TYPES.put("pm", "text/plain");
    SAVE_MIME_TYPES.put("dart", "text/plain");
    SAVE_MIME_TYPES.put("scala", "text/plain");
    SAVE_MIME_TYPES.put("proto", "text/plain");
    SAVE_MIME_TYPES.put("graphql", "text/plain");
    SAVE_MIME_TYPES.put("gql", "text/plain");
    SAVE_MIME_TYPES.put("tex", "text/plain");
    SAVE_MIME_TYPES.put("rst", "text/plain");
    SAVE_MIME_TYPES.put("adoc", "text/plain");
    SAVE_MIME_TYPES.put("srt", "text/plain");
    SAVE_MIME_TYPES.put("vtt", "text/plain");
    SAVE_MIME_TYPES.put("ipynb", "text/plain");
    SAVE_MIME_TYPES.put("gitignore", "text/plain");
    SAVE_MIME_TYPES.put("gitattributes", "text/plain");
    SAVE_MIME_TYPES.put("editorconfig", "text/plain");
    SAVE_MIME_TYPES.put("npmrc", "text/plain");
    SAVE_MIME_TYPES.put("xml", "application/xml");
  }

  private OpenFormats() {}

  /** The MIME type a new document is created with, so providers keep its extension. */
  static String mimeTypeFor(String fileName) {
    String normalized = fileName.toLowerCase(Locale.ROOT);
    int dot = normalized.lastIndexOf('.');
    String mimeType = dot < 0 ? null : SAVE_MIME_TYPES.get(normalized.substring(dot + 1));
    return mimeType != null
        ? mimeType
        : "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  }
}
