"""English starter copy for the CubeOffice original templates.

The words are placeholders a user replaces, so they are written to be useful on
the way out: each line shows what belongs in that slot rather than saying
"Lorem ipsum". `BASE` holds the slots that read the same whatever the deck is
about; every template overrides the rest.
"""

BASE = {
    "agenda_title": "What we will cover",
    "cover_footer": "Your team · Your organization · Month 2026",
    "picture_title": "One image, one idea",
    "picture_eyebrow": "Evidence",
    "picture_hint": "Drop an image here",
    "picture_caption": "Caption the image: what it shows and where it came from.",
    "table_note": "Replace the rows with your own figures. Keep one unit per column.",
    "closing_contact": "your.name@example.com · +00 000 0000 · example.com",
    "monogram": "M",
}

CONTENT = {
    "meridian": {
        "kicker": "Business plan · FY2026",
        "title": "A plan we can fund and defend",
        "subtitle": "The market we are entering, the product we will sell, and what it costs to get there.",
        "agenda_items": [
            ("The market", "Who is buying today and how fast that is changing."),
            ("Our opening", "The gap we can reach before anyone else does."),
            ("The product", "What we build first and what we deliberately leave out."),
            ("The model", "How a customer becomes revenue, and at what margin."),
            ("The plan", "Twelve months, four milestones, named owners."),
            ("The ask", "What we need, and what it buys."),
        ],
        "sections": [
            ("The market", "Size, structure and where the money currently goes."),
            ("The plan", "What we do in the next four quarters."),
            ("The ask", "Capital, hiring and the returns we underwrite."),
        ],
        "lead_eyebrow": "Thesis",
        "lead_title": "Why this, and why now",
        "lead_body": "State the thesis in three sentences. Name the change in the market, the reason the current answer no longer fits, and the specific position you intend to hold. A reader should be able to repeat it back after one pass.",
        "lead_points": [
            "The change: what shifted in the last 18 months.",
            "The gap: what customers now do instead, and what it costs them.",
            "Our claim: the one thing we do better than the alternative.",
            "The proof: the evidence we already hold.",
        ],
        "cards_eyebrow": "Approach",
        "cards_title": "Three commitments",
        "cards": [
            ("Focus", "One segment, one problem, until it is unambiguously solved."),
            ("Margin", "Price on the value delivered, not on the cost to build."),
            ("Discipline", "Every quarter has one milestone that can be judged pass or fail."),
        ],
        "stats_eyebrow": "The numbers",
        "stats_title": "What the plan assumes",
        "stats": [
            ("$4.2M", "Revenue, year 2", "Bottom-up from named accounts."),
            ("62%", "Gross margin", "At the pricing in the model tab."),
            ("14", "Headcount", "Nine in delivery, five in go-to-market."),
            ("18 mo", "Runway", "From close, at the plan's burn."),
        ],
        "stats_footnote": "Every figure traces to the model. Change an assumption there and this slide changes with it.",
        "timeline_eyebrow": "Twelve months",
        "timeline_title": "Milestones and owners",
        "timeline": [
            ("Q1", "Design partners", "Three signed, paid, and using it weekly."),
            ("Q2", "General release", "Self-serve onboarding without a call."),
            ("Q3", "First channel", "One partner producing repeatable volume."),
            ("Q4", "Second segment", "Adjacent buyer, same product."),
            ("Q1+", "Scale", "Hiring against proven unit economics."),
        ],
        "timeline_done": 2,
        "table_eyebrow": "Use of funds",
        "table_title": "Where the money goes",
        "table_header": ["Area", "Year 1", "Year 2", "Share"],
        "table_rows": [
            ["Engineering", "$980K", "$1.6M", "46%"],
            ["Go-to-market", "$520K", "$1.1M", "31%"],
            ["Operations", "$240K", "$420K", "13%"],
            ["Reserve", "$180K", "$300K", "10%"],
        ],
        "picture_lead": "Show the thing itself",
        "picture_body": "One screenshot of the product doing the job, or one chart that makes the claim unarguable. Not a stock photograph, and not a diagram of the org.",
        "quote": "We did not need another dashboard. We needed the number to be right the first time.",
        "quote_attribution": "Design partner, operations lead",
        "closing_title": "The ask",
        "closing_body": "Name the amount, the instrument, and the two decisions you want made in this room today.",
    },
    "kinetic": {
        "kicker": "Launch · Version 2.0",
        "title": "Ship it loud",
        "subtitle": "What changed, who it is for, and how we tell them on day one.",
        "agenda_items": [
            ("The release", "What is actually in the box."),
            ("Who it is for", "The user whose day this changes."),
            ("The headline", "One sentence, no adjectives."),
            ("Proof", "The demo and the numbers behind it."),
            ("Launch week", "Sequence, owners, dependencies."),
            ("After launch", "What we watch, and what we do about it."),
        ],
        "sections": [
            ("The release", "Everything shipping, and everything deliberately held back."),
            ("The story", "How we say it so it lands in one read."),
            ("Launch week", "Hour by hour, with names attached."),
        ],
        "lead_eyebrow": "Positioning",
        "lead_title": "One sentence, no adjectives",
        "lead_body": "Write the headline you want repeated back to you. It should name the user, the job and the change — and survive being read out loud. If it needs a second sentence to make sense, it is not finished.",
        "lead_points": [
            "For whom: the specific user, not the market.",
            "Instead of what: the thing they stop doing.",
            "So that: the outcome they can measure by Friday.",
            "Proof: the one number or demo that settles it.",
        ],
        "cards_eyebrow": "What shipped",
        "cards_title": "Three things that matter",
        "cards": [
            ("Faster", "The path that used to take six steps now takes two."),
            ("Clearer", "One place to see status, with no refresh."),
            ("Safer", "Undo everywhere, including the parts that used to be final."),
        ],
        "stats_eyebrow": "Readiness",
        "stats_title": "Where we stand",
        "stats": [
            ("2.0", "Version", "Feature-complete and frozen."),
            ("94%", "Tests green", "Remaining failures triaged as known."),
            ("31", "Beta accounts", "Four weeks of daily use."),
            ("0", "Blockers", "Open list reviewed this morning."),
        ],
        "stats_footnote": "Update this the morning of launch, not the week before. A stale readiness slide is worse than none.",
        "timeline_eyebrow": "Launch week",
        "timeline_title": "The sequence",
        "timeline": [
            ("Mon", "Freeze", "Build tagged, notes written, nothing merges."),
            ("Tue", "Brief", "Support and sales get the demo and the FAQ."),
            ("Wed", "Ship", "Staged rollout, 10% then all."),
            ("Thu", "Tell", "Post, mail, and the two calls that matter."),
            ("Fri", "Listen", "Triage, hotfix window, first read on adoption."),
        ],
        "timeline_done": 3,
        "table_eyebrow": "Owners",
        "table_title": "Who does what",
        "table_header": ["Workstream", "Owner", "Ready by", "State"],
        "table_rows": [
            ["Release build", "Engineering", "Mon 09:00", "Done"],
            ["Docs and FAQ", "Support", "Tue 12:00", "In review"],
            ["Announcement", "Marketing", "Wed 08:00", "Drafted"],
            ["Rollout gate", "On-call", "Wed 14:00", "Scheduled"],
        ],
        "picture_lead": "Lead with the demo",
        "picture_body": "One frame of the product doing the new thing. If the change is hard to photograph, show the before and after side by side and let the difference argue for itself.",
        "quote": "It took four clicks and a support ticket. Now it takes one and no ticket.",
        "quote_attribution": "Beta account, week three",
        "closing_title": "Go or no-go",
        "closing_body": "State the decision you need, the time you need it by, and who says yes.",
    },
    "lattice": {
        "kicker": "Annual report · 2026",
        "title": "The year in figures",
        "subtitle": "What we set out to do, what the numbers say we did, and what we changed our minds about.",
        "agenda_items": [
            ("The year", "The three decisions that shaped it."),
            ("Results", "Revenue, margin, retention, headcount."),
            ("Segments", "Where growth came from and where it did not."),
            ("Investment", "What we funded and what we stopped."),
            ("Risk", "What we watch, and our current view."),
            ("Next year", "The plan in one page."),
        ],
        "sections": [
            ("Results", "Audited figures against the plan we published."),
            ("Segments", "Performance by market, product and channel."),
            ("Outlook", "Assumptions, ranges and the risks around them."),
        ],
        "lead_eyebrow": "Letter",
        "lead_title": "What the year taught us",
        "lead_body": "Open with the honest summary: the target, the result, and the gap. Readers who trust the first paragraph read the rest. Name one thing that went badly and what you did about it — it buys credibility for everything that follows.",
        "lead_points": [
            "Target versus actual, stated plainly.",
            "The one decision that moved the number most.",
            "The one that did not work, and its cost.",
            "What we are carrying into next year.",
        ],
        "cards_eyebrow": "Segments",
        "cards_title": "Where growth came from",
        "cards": [
            ("Core", "Steady, high margin, and the source of most of the cash."),
            ("Expansion", "Fastest growth, thinnest margin, most of the hiring."),
            ("New", "Small base, unproven, funded as an option not a bet."),
        ],
        "stats_eyebrow": "Results",
        "stats_title": "The headline figures",
        "stats": [
            ("+23%", "Revenue", "Against +18% in the published plan."),
            ("58%", "Gross margin", "Down two points on mix, not on price."),
            ("94%", "Net retention", "Churn concentrated in one cohort."),
            ("2.1x", "Cash cover", "Operating cash to fixed cost."),
        ],
        "stats_footnote": "Figures are for the twelve months to 31 December. Prior-year comparatives are restated on the current segment basis.",
        "timeline_eyebrow": "The year",
        "timeline_title": "How it unfolded",
        "timeline": [
            ("Q1", "Repriced", "New tiers, applied to renewals first."),
            ("Q2", "Consolidated", "Two products merged into one line."),
            ("Q3", "Expanded", "Second region opened with a local partner."),
            ("Q4", "Tightened", "Hiring paused; margin recovered a point."),
            ("2027", "Outlook", "Growth ahead of market, margin held flat."),
        ],
        "timeline_done": 4,
        "table_eyebrow": "Segments",
        "table_title": "Performance by segment",
        "table_header": ["Segment", "Revenue", "Growth", "Margin"],
        "table_rows": [
            ["Core", "$18.4M", "+9%", "64%"],
            ["Expansion", "$7.9M", "+58%", "41%"],
            ["New markets", "$1.2M", "+140%", "22%"],
            ["Total", "$27.5M", "+23%", "58%"],
        ],
        "picture_lead": "One chart, not four",
        "picture_body": "Pick the single series that carries the year and give it a whole page. Label the axis, name the unit, and put the source underneath. Everything else belongs in the appendix.",
        "quote": "The plan was right about direction and wrong about pace. We would rather say so than restate it.",
        "quote_attribution": "Chief executive, annual letter",
        "closing_title": "Next year",
        "closing_body": "Three commitments, each with a number attached and a date by which it can be judged.",
    },
    "tidewater": {
        "kicker": "Sales strategy · H1 2026",
        "title": "Fewer deals, better deals",
        "subtitle": "Where we compete, how we qualify, and what we stop chasing.",
        "agenda_items": [
            ("The pipeline", "What is really in it, at what stage."),
            ("Where we win", "The pattern in the deals we close."),
            ("Where we lose", "The pattern in the ones we do not."),
            ("Qualification", "The bar, and who enforces it."),
            ("Coverage", "Territories, quotas, capacity."),
            ("The half", "Targets and the review cadence."),
        ],
        "sections": [
            ("Diagnosis", "What the pipeline data actually says."),
            ("The play", "Segment, message, motion."),
            ("Execution", "Coverage, quota and cadence."),
        ],
        "lead_eyebrow": "Diagnosis",
        "lead_title": "We are not short of leads",
        "lead_body": "State the real constraint. Most teams do not lose for lack of pipeline; they lose because too much of it never qualified. Say which stage leaks, by how much, and what you believe causes it — then commit to one change rather than five.",
        "lead_points": [
            "Stage-two to stage-three is where the volume disappears.",
            "Deals with a named economic buyer close at three times the rate.",
            "Cycle length doubles without a written success criterion.",
            "One change this half: qualification, enforced at review.",
        ],
        "cards_eyebrow": "The play",
        "cards_title": "Three moves",
        "cards": [
            ("Narrow", "Two segments, named accounts, nothing outside the list."),
            ("Qualify", "No stage three without a buyer, a budget and a date."),
            ("Prove", "Every deal carries one reference the buyer can call."),
        ],
        "stats_eyebrow": "Pipeline",
        "stats_title": "Where we stand today",
        "stats": [
            ("3.1x", "Coverage", "Against a 4x target for the half."),
            ("38%", "Stage-3 win rate", "Up from 29% on qualified deals only."),
            ("71 d", "Cycle length", "Median, from first meeting to signature."),
            ("$46K", "Average deal", "Flat; mix, not discounting."),
        ],
        "stats_footnote": "Coverage is qualified pipeline over quota. Unqualified opportunities are excluded on purpose.",
        "timeline_eyebrow": "The half",
        "timeline_title": "Cadence",
        "timeline": [
            ("Wk 1", "Reset", "Pipeline scrubbed against the new bar."),
            ("Wk 2", "Retrain", "One workshop, one script, one checklist."),
            ("Wk 6", "First read", "Win rate and cycle length by segment."),
            ("Wk 12", "Adjust", "Territory and quota correction if needed."),
            ("Wk 24", "Close", "Half reviewed against the two targets."),
        ],
        "timeline_done": 2,
        "table_eyebrow": "Coverage",
        "table_title": "Territories and quota",
        "table_header": ["Territory", "Reps", "Quota", "Coverage"],
        "table_rows": [
            ["North", "4", "$2.4M", "3.6x"],
            ["South", "3", "$1.8M", "2.9x"],
            ["Enterprise", "2", "$2.0M", "3.4x"],
            ["Partner", "1", "$0.6M", "2.1x"],
        ],
        "picture_lead": "Show the funnel, not the forecast",
        "picture_body": "A stage-by-stage conversion chart tells the team where to work. A forecast number tells them how nervous to be. Put the first one on the wall and keep the second in the review.",
        "quote": "The deals we lost were the ones we should never have worked.",
        "quote_attribution": "Regional lead, quarterly review",
        "closing_title": "What we are asking for",
        "closing_body": "Two headcount, one enablement week, and permission to disqualify without escalation.",
    },
    "ledger": {
        "kicker": "Status report · Week 24",
        "title": "Project status",
        "subtitle": "Scope, schedule, risk and the two decisions we need from this meeting.",
        "agenda_items": [
            ("Headline", "One line: on track, at risk, or off track."),
            ("Progress", "What closed since the last report."),
            ("Schedule", "Milestones, and any date that moved."),
            ("Risks", "Ranked, with an owner and a next action."),
            ("Budget", "Spend against plan, and the forecast."),
            ("Decisions", "What we need agreed today."),
        ],
        "sections": [
            ("Progress", "Delivered, in flight, and not started."),
            ("Risk", "What could move the date, ranked by exposure."),
            ("Decisions", "The choices that need an owner in this room."),
        ],
        "lead_eyebrow": "Headline",
        "lead_title": "On track, with one date at risk",
        "lead_body": "Lead with the verdict, not the narrative. State the overall status in one sentence, name the single thing most likely to change it, and say what you need in order to hold the date. Detail follows for the people who want it.",
        "lead_points": [
            "Overall: on track for the September milestone.",
            "At risk: the integration date, pending a third-party fix.",
            "Mitigation: parallel path agreed, costs two weeks of effort.",
            "Needed today: a decision on scope for the second phase.",
        ],
        "cards_eyebrow": "Workstreams",
        "cards_title": "Three streams, three states",
        "cards": [
            ("Delivery", "On plan. Six of eight components accepted."),
            ("Integration", "At risk. Blocked on an external dependency."),
            ("Rollout", "Not started. Begins once integration is accepted."),
        ],
        "stats_eyebrow": "This period",
        "stats_title": "Progress and spend",
        "stats": [
            ("74%", "Scope complete", "Accepted deliverables over total."),
            ("+3 d", "Schedule variance", "Against the baseline plan."),
            ("68%", "Budget used", "At 74% of scope — favourable."),
            ("2", "Open risks", "Both with an owner and a date."),
        ],
        "stats_footnote": "Variance is measured against the baseline agreed in week 4, not against the last report.",
        "timeline_eyebrow": "Milestones",
        "timeline_title": "Where the date stands",
        "timeline": [
            ("Wk 4", "Baseline", "Scope and plan agreed and frozen."),
            ("Wk 12", "Build start", "Environments handed over."),
            ("Wk 24", "Integration", "External dependency outstanding."),
            ("Wk 32", "Acceptance", "User testing, two-week window."),
            ("Wk 36", "Live", "Phased cutover, rollback rehearsed."),
        ],
        "timeline_done": 2,
        "table_eyebrow": "Risk register",
        "table_title": "Ranked risks",
        "table_header": ["Risk", "Impact", "Owner", "Next action"],
        "table_rows": [
            ["Third-party fix late", "High", "Integration lead", "Escalate Friday"],
            ["Test data incomplete", "Medium", "Delivery lead", "Sourced by wk 26"],
            ["Key person single point", "Medium", "Programme", "Pairing from wk 25"],
            ["Scope creep, phase 2", "Low", "Sponsor", "Decision today"],
        ],
        "picture_lead": "One chart the sponsor can read",
        "picture_body": "Burn-up against the baseline, or milestones against dates. Whichever you pick, keep it the same chart every report — a sponsor should be able to compare this week to last week without re-reading the axis.",
        "quote": "Tell me the date is moving in week 24, not in week 34.",
        "quote_attribution": "Programme sponsor",
        "closing_title": "Decisions needed",
        "closing_body": "Two: the phase-two scope, and whether we fund the parallel integration path.",
    },
    "chalk": {
        "kicker": "Workshop · Module 1 of 4",
        "title": "Learning by doing",
        "subtitle": "What you will be able to do by the end of the session, and how we get there.",
        "agenda_items": [
            ("Outcomes", "What you can do afterwards that you cannot now."),
            ("Warm-up", "A short exercise to surface what you already know."),
            ("Concept", "The smallest amount of theory that is genuinely needed."),
            ("Practice", "The main exercise, in pairs."),
            ("Review", "What went wrong, and why that is the useful part."),
            ("Take-away", "One page you keep, and one thing you try this week."),
        ],
        "sections": [
            ("Outcomes", "What this session is for, stated as things you can do."),
            ("Practice", "The exercise, the constraints and the debrief."),
            ("Take-away", "What to keep, and what to try before we meet again."),
        ],
        "lead_eyebrow": "Outcomes",
        "lead_title": "By the end of this session",
        "lead_body": "Write outcomes as observable actions, not topics covered. \"Understand the process\" cannot be checked; \"run the process on your own data and explain the result\" can. Three outcomes is plenty for ninety minutes.",
        "lead_points": [
            "Run the process end to end on a real example.",
            "Explain each step to someone who was not here.",
            "Spot the two mistakes that cause most of the rework.",
            "Know where to look when it goes wrong.",
        ],
        "cards_eyebrow": "How the session runs",
        "cards_title": "Three parts",
        "cards": [
            ("Show", "Fifteen minutes. One worked example, start to finish."),
            ("Do", "Forty minutes. Your own data, in pairs, with help on call."),
            ("Debrief", "Twenty minutes. What broke, and what to do next time."),
        ],
        "stats_eyebrow": "Shape of the session",
        "stats_title": "Ninety minutes",
        "stats": [
            ("15", "Minutes shown", "One example, no slides after this."),
            ("40", "Minutes practised", "Hands on keyboards, in pairs."),
            ("20", "Minutes debriefed", "Mistakes first, then fixes."),
            ("1", "Page to keep", "The checklist, printed."),
        ],
        "stats_footnote": "Timings are deliberate. If the practice block shrinks, the session stops working — cut the theory instead.",
        "timeline_eyebrow": "The course",
        "timeline_title": "Four modules",
        "timeline": [
            ("M1", "Foundations", "The process, run once, on a clean example."),
            ("M2", "Your data", "The same process against real, messy inputs."),
            ("M3", "When it breaks", "Diagnosis, and the three usual causes."),
            ("M4", "Teaching it", "You run the exercise; we watch."),
            ("After", "Practice", "One review session at four weeks."),
        ],
        "timeline_done": 1,
        "table_eyebrow": "Before you arrive",
        "table_title": "What to bring",
        "table_header": ["Item", "Why", "Who", "By when"],
        "table_rows": [
            ["A laptop", "The practice block is hands-on", "Everyone", "On the day"],
            ["Your own dataset", "Practice on real inputs", "Everyone", "Day before"],
            ["Access to the tool", "No time to fix logins", "Everyone", "Day before"],
            ["One question", "We answer them in the debrief", "Everyone", "On the day"],
        ],
        "picture_lead": "Show the worked example",
        "picture_body": "A screenshot of the finished exercise gives people something to aim at. Put it up before they start, leave it up while they work, and refer back to it in the debrief.",
        "quote": "I had read the guide twice. I only understood it once I broke it myself.",
        "quote_attribution": "Participant, previous cohort",
        "closing_title": "Before next time",
        "closing_body": "Try the process once on your own work. Bring what went wrong — that is the material for module two.",
    },
    "passepartout": {
        "kicker": "Selected work · 2023–2026",
        "title": "Portfolio",
        "subtitle": "Six projects, what each one was for, and what I actually did on it.",
        "agenda_items": [
            ("About", "What I do, and the kind of work I take on."),
            ("Selected work", "Six projects, most recent first."),
            ("Process", "How a project runs from brief to hand-off."),
            ("Detail", "One project, followed all the way through."),
            ("Results", "What changed for the client, in their numbers."),
            ("Contact", "How to start a conversation."),
        ],
        "sections": [
            ("Selected work", "Six projects. Brief, role, outcome."),
            ("In detail", "One project, from first sketch to shipped."),
            ("Working together", "Process, timelines and what I need from you."),
        ],
        "lead_eyebrow": "About",
        "lead_title": "What I do",
        "lead_body": "Two or three sentences, in the first person, that a stranger can act on. Name the discipline, the kind of client, and the part of the problem you take responsibility for. Leave the adjectives out; the work is on the next page.",
        "lead_points": [
            "Discipline: what you are actually hired to do.",
            "Clients: the sort of organization you work with.",
            "Scope: where you start and where you hand over.",
            "Availability: how far out you are booked.",
        ],
        "cards_eyebrow": "How I work",
        "cards_title": "Three phases",
        "cards": [
            ("Frame", "A week. Understand the problem well enough to scope it."),
            ("Make", "Four to eight weeks. Weekly reviews, nothing kept back."),
            ("Hand over", "A week. Files, documentation and one walkthrough."),
        ],
        "stats_eyebrow": "Track record",
        "stats_title": "In numbers",
        "stats": [
            ("42", "Projects", "Since 2019, across six sectors."),
            ("8", "Long-term clients", "Two or more engagements."),
            ("6 wk", "Typical length", "From frame to hand-over."),
            ("100%", "Delivered", "No project abandoned mid-way."),
        ],
        "stats_footnote": "Numbers are only useful if they are checkable. Keep to the ones a client could verify by asking a reference.",
        "timeline_eyebrow": "One project",
        "timeline_title": "Brief to shipped",
        "timeline": [
            ("Wk 1", "Brief", "Interviews, constraints, success criteria written down."),
            ("Wk 2", "Directions", "Three routes, one recommendation."),
            ("Wk 4", "Build", "Chosen route, developed weekly in the open."),
            ("Wk 6", "Test", "With real users, on real content."),
            ("Wk 7", "Hand over", "Assets, documentation, one training session."),
        ],
        "timeline_done": 5,
        "table_eyebrow": "Selected work",
        "table_title": "Six projects",
        "table_header": ["Project", "Client", "Role", "Year"],
        "table_rows": [
            ["Identity and site", "Independent gallery", "Lead", "2026"],
            ["Product photography", "Furniture maker", "Photographer", "2025"],
            ["Exhibition graphics", "City museum", "Designer", "2025"],
            ["Annual report", "Regional charity", "Art direction", "2024"],
        ],
        "picture_lead": "Let the work be the argument",
        "picture_body": "One image per page, as large as the page allows, with a caption that says what it is and what you did on it. Resist the urge to explain the concept — if the image needs a paragraph, choose a different image.",
        "quote": "They sent three directions and told us which one to pick, and why. That is the whole job.",
        "quote_attribution": "Gallery director, 2026",
        "closing_title": "Let's talk",
        "closing_body": "Tell me what the project is, when it needs to be finished, and what you have already tried.",
    },
    "monogram": {
        "kicker": "Presentation",
        "title": "Say one thing",
        "subtitle": "A neutral template for any subject: type, space, and a single accent.",
        "monogram": "A",
        "agenda_items": [
            ("Point", "The one thing you want remembered."),
            ("Context", "Why it matters now."),
            ("Evidence", "What makes it credible."),
            ("Objection", "The strongest argument against."),
            ("Answer", "Why the objection does not change the decision."),
            ("Ask", "What you want the room to do."),
        ],
        "sections": [
            ("The point", "Stated once, in full, before any detail."),
            ("The evidence", "Three items, strongest first."),
            ("The ask", "One decision, one owner, one date."),
        ],
        "lead_eyebrow": "The point",
        "lead_title": "Say it before you explain it",
        "lead_body": "Put the conclusion on the first slide. An audience that knows where you are going can follow an argument; one that is waiting for the reveal is only guessing. Explain afterwards, for as long as the room needs.",
        "lead_points": [
            "The claim, in one sentence.",
            "The reason it is true.",
            "The reason it matters today.",
            "The decision it implies.",
        ],
        "cards_eyebrow": "Structure",
        "cards_title": "Three moves",
        "cards": [
            ("Claim", "One sentence. No hedging, no adjectives."),
            ("Support", "Three pieces of evidence, strongest first."),
            ("Ask", "The specific decision, and who makes it."),
        ],
        "stats_eyebrow": "Evidence",
        "stats_title": "Four figures",
        "stats": [
            ("18%", "First figure", "What it measures and over what period."),
            ("2.4x", "Second figure", "The comparison that makes it meaningful."),
            ("$1.1M", "Third figure", "The amount at stake in the decision."),
            ("6 wk", "Fourth figure", "How long the window stays open."),
        ],
        "stats_footnote": "Four numbers is the most an audience will retain. Put the rest in the appendix and say that you have.",
        "timeline_eyebrow": "Sequence",
        "timeline_title": "What happens next",
        "timeline": [
            ("Now", "Decide", "One decision, made in this room."),
            ("Wk 1", "Assign", "Owner named, scope written down."),
            ("Wk 3", "First check", "Evidence that it is working, or not."),
            ("Wk 6", "Review", "Continue, adjust or stop."),
            ("Wk 12", "Result", "Measured against the figure on slide six."),
        ],
        "timeline_done": 1,
        "table_eyebrow": "Comparison",
        "table_title": "The options",
        "table_header": ["Option", "Cost", "Time", "Risk"],
        "table_rows": [
            ["Do nothing", "None", "—", "High"],
            ["Fix in place", "Low", "6 weeks", "Medium"],
            ["Replace", "High", "6 months", "Low"],
            ["Recommended", "Low", "6 weeks", "Medium"],
        ],
        "picture_lead": "One image, if any",
        "picture_body": "A neutral template invites decoration. Resist it. Use an image only when it carries information the words cannot — a photograph of the thing, a chart of the change, a screenshot of the problem.",
        "quote": "If you cannot say it in a sentence, you do not yet know what you think.",
        "quote_attribution": "Attribute the quote, or cut it",
        "closing_title": "The ask",
        "closing_body": "One decision. Name it, name who makes it, and name the date it stops being useful.",
    },
}

for _key, _entry in CONTENT.items():
    for _field, _value in BASE.items():
        _entry.setdefault(_field, _value)
