// Generated by scripts/sync-open-formats.mjs from scripts/open-formats.mjs. Do not edit directly.
import Foundation
import UniformTypeIdentifiers

/// The formats the picker offers, the same list the Android and HarmonyOS hosts use.
///
/// Several of these have no system-declared type — OFD, Visio, JMP, draw.io — so the
/// app declares them itself in `Info.plist` (`UTImportedTypeDeclarations`), which is
/// what makes `UTType(filenameExtension:)` resolve them here and what puts the app in
/// the Files app's "Open with" list for those documents.
enum DocumentTypes {
	static let extensions: [String] = [
		"docx",
		"doc", "dot",
		"pptx",
		"ppt", "pps", "pot",
		"xlsx",
		"xlsm",
		"xls", "xlt",
		"csv",
		"tsv",
		"jmp",
		"vsdx",
		"vsd", "vss", "vst",
		"drawio",
		"pdf",
		"ofd",
		"md", "markdown",
		"png",
		"jpg", "jpeg",
		"webp",
		"emf",
		"wmf",
		"gif",
		"bmp", "dib",
		"svg",
		"tif", "tiff",
		"heic", "heif", "hif",
		"txt", "log", "java", "js", "mjs", "cjs", "jsx", "ts", "mts", "cts", "tsx", "json", "jsonl", "jsonc", "html", "htm", "css", "scss", "less", "vue", "py", "pyw", "rb", "sh", "bash", "zsh", "yml", "yaml", "toml", "ini", "conf", "cfg", "properties", "env", "c", "h", "cpp", "hpp", "cc", "cxx", "cs", "go", "rs", "sql", "php", "swift", "kt", "kts", "diff", "patch", "gradle", "groovy", "dockerfile", "makefile", "ps1", "psm1", "bat", "cmd", "lua", "r", "pl", "pm", "dart", "scala", "proto", "graphql", "gql", "tex", "rst", "adoc", "srt", "vtt", "ipynb", "gitignore", "gitattributes", "editorconfig", "npmrc",
		"xml",
	]

	static let openable: [UTType] = {
		var seen = Set<String>()
		var types = extensions.compactMap { UTType(filenameExtension: $0) }
			.filter { seen.insert($0.identifier).inserted }
		// Android's list ends in application/octet-stream for the same reason: a document
		// arriving from a cloud provider often carries no recognisable type at all, and
		// the editor decides by content once it is open.
		types.append(.data)
		return types
	}()
}
