/** Installed debug APK regression. Uses the actual Android WebView, never desktop emulation.
 * ADB_PATH=/path/to/adb PLAYWRIGHT_MODULE_PATH=/path/to/playwright node apps/android/tests/emulator.cjs
 * Leaves its test drafts on the emulator; does not clear app data or submit feedback.
 */
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const { _android } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const adbPath = process.env.ADB_PATH || 'adb';
const serial = process.env.ANDROID_SERIAL || 'emulator-5554';
const output = process.env.ANDROID_QA_OUTPUT || '/tmp/cubeoffice-emulator-qa';
fs.mkdirSync(output, { recursive: true });
const adb = (...args) => execFileSync(adbPath, ['-s', serial, ...args]);
(async () => {
 const devices = await _android.devices();
 const device = devices.find(d => d.serial() === serial);
 assert(device, `Connect ${serial} first`);
 const errors = [];
 try {
  const page = await (await device.webView({ pkg: 'com.cubexp.office' })).page();
  page.setDefaultTimeout(20000);
  await page.emulateMedia({colorScheme:null});
  page.on('pageerror', error => errors.push(error.message));
  const button = name => page.getByRole('button', { name, exact: true });
  const shot = async name => {
   await page.waitForTimeout(300); // Capture settled transitions, not an animation frame.
   fs.writeFileSync(path.join(output, name + '.png'), adb('exec-out', 'screencap', '-p'));
  };
  const create = async name => {
   await button('新建').click();
   await page.locator('.android-sheet').getByRole('button', { name: new RegExp(name) }).click();
   if (name === '演示文稿') await button('空白演示文稿').click();
   await button('格式').waitFor();
  };
  const home = async () => {
   await button('完成编辑').click();
   await button('返回').click();
   await button('新建').waitFor();
  };
  await button('新建').waitFor();
  await button('设置').click();
  await button('意见反馈').click();
  const settingsY = await page.locator('.android-library-scroll').evaluate(e => e.scrollTop);
  assert(settingsY > 0);
  await button('文件').click();
  assert.equal(await page.locator('.android-library-scroll').evaluate(e => e.scrollTop), 0);
  await button('设置').click();
  assert(Math.abs(await page.locator('.android-library-scroll').evaluate(e => e.scrollTop) - settingsY) < 2);
  await button('收起反馈表单').click();
  await button('文件').click();
  await page.getByRole('searchbox').fill('QA-no-such-document-20260911');
  await page.getByRole('heading', { name: '没有匹配的文档' }).waitFor();
  await button('清除筛选').click();
  console.log('PASS navigation scroll restoration / search / empty state');
  await create('文字文档');
  await button('格式').click();
  await button('加粗').click();
  assert.equal(await button('加粗').getAttribute('aria-pressed'), 'true');
  await button('关闭格式面板').click();
  const canvas = page.locator('.harmony-documents__surface[data-active="true"] .als-ofs-docx-word-canvas__document');
  await canvas.click({ position: { x: 80, y: 80 } });
  await page.keyboard.type('OfficeABC', { delay: 150 });
  assert.equal((await canvas.innerText()).trim(), 'OfficeABC', 'formatted typing must not replace preceding characters');
  await page.keyboard.press('Enter');
  await page.keyboard.type('Second', { delay: 150 });
  assert.match(await canvas.innerText(), /OfficeABC[\s\S]*Second/);
  await button('收起键盘').click();
  await button('撤销').click();
  await button('更多文档操作').click();
  await button('重做').click();
  assert.match(await canvas.innerText(), /Second/);
  await shot('word');
  await home();
  console.log('PASS Word bold typing / paragraph / undo-redo / draft');
  await create('电子表格');
  const formula = page.locator('.harmony-documents__surface[data-active="true"] .als-ofs-xlsx-formula-input');
  await formula.fill('=SUM(1,2)');
  await formula.press('Enter');
  const nameBox = page.locator('.harmony-documents__surface[data-active="true"] .als-ofs-xlsx-name-box');
  await nameBox.fill('A1');
  await nameBox.press('Enter');
  await page.getByText('Sheet1, A1, 3', {exact:true}).waitFor();
  assert.equal(await formula.inputValue(), '=SUM(1,2)');
  await button('格式').click();
  await page.locator('.android-ribbon-header').waitFor();
  await button('关闭面板').click();
  await button('插入').click();
  await button('关闭面板').click();
  await shot('spreadsheet');
  await home();
  console.log('PASS spreadsheet formula / format / insert / draft');
  await create('演示文稿');
  await button('新幻灯片').click();
  await page.waitForFunction(() => document.querySelectorAll('.harmony-documents__surface[data-active="true"] .als-ofs-pptx-slide-frame').length === 2);
  await button('完成编辑').click();
  await button('播放').click();
  await page.waitForFunction(() => innerWidth > innerHeight);
  await shot('presentation');
  adb('shell', 'input', 'keyevent', '4');
  await button('返回').waitFor();
  await button('返回').click();
  console.log('PASS presentation add slide / native landscape playback / native Back');
  await create('流程图');
  await button('插入').click();
  await button('流程').click();
  await button('关闭面板').click();
  await shot('diagram');
  await home();
  console.log('PASS diagram insert / draft');
  await create('Markdown');
  const source = page.locator('.harmony-documents__surface[data-active="true"] .als-ofs-ui-markdown-editor__source-input');
  await source.fill('# Android QA\n\nPersistence check 20260911');
  await button('完成编辑').click();
  await page.getByRole('heading', { name: 'Android QA' }).waitFor();
  await button('返回').click();
  const file = page.locator('.android-file-row').filter({hasText:'Notes.md'}).first();
  await file.click();
  await page.getByRole('heading', { name: 'Android QA' }).waitFor();
  await button('返回').click();
  await shot('home');
  console.log('PASS Markdown editing / reading / reopen');
  await page.locator('.android-file-input').setInputFiles(path.resolve(__dirname, '../../../als-office/packages/pdf/tests/fixtures/ai-readable-sample.pdf'));
  await page.locator('.android-document-title strong').filter({hasText:'ai-readable-sample.pdf'}).waitFor();
  await page.locator('.android-editor-tools button[aria-label=查找]').click();
  await page.locator('.als-ofs-ui-search-box__input').fill('Revenue');
  await page.locator('.als-ofs-ui-search-box__input').press('Enter');
  await page.locator('.als-ofs-pdf-page-canvas__search-highlight--current').waitFor();
  await shot('pdf-search');
  adb('shell', 'input', 'keyevent', '4');
  await button('返回').click();
  console.log('PASS PDF file import / text search highlight');
  assert.deepEqual(errors, [], 'No uncaught WebView exceptions');
  console.log('PASS actual Android WebView suite');
 } finally { await device.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
