const fs = require('fs');
const ts = require(process.cwd()+'/node_modules/typescript');
const assert = require('node:assert/strict');
(async () => {
 const source=fs.readFileSync('apps/harmony/web/src/services/client-services.ts','utf8');
 const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
 const m=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
 const good={versionCode:1002001,versionName:'1.2.0',minSdk:26,url:'https://cubexp.com/downloads/CubeOffice-1.2.0-Android.apk',sha256:'a'.repeat(64)};
 assert.equal(m.validateRelease(good).versionCode,1002001);
 for(const patch of [{url:'http://cubexp.com/a.apk'},{url:'https://evil.com/a.apk'},{url:'https://cubexp.com@evil.com/a.apk'},{sha256:'bad'},{minSdk:0},{versionCode:1.2},{versionName:'bad'}]) assert.throws(()=>m.validateRelease({...good,...patch}));
 global.window={cubeofficeServices:{request:()=> 'id',takeResult:()=> JSON.stringify({ok:true,data:good})}};
 assert.deepEqual(await m.requestService('updates'),good);
 window.cubeofficeServices.takeResult=()=> JSON.stringify({ok:false,error:'offline'});
 await assert.rejects(m.requestService('feedback'),/offline/);
 window.cubeofficeServices.request=()=>'';
 await assert.rejects(m.requestService('updates'),/正在进行/);
 delete window.cubeofficeServices;
 await assert.rejects(m.requestService('updates'),/当前客户端/);
 assert.equal(m.updateChannel({platform:'harmonyos',updateChannel:'website'}),'appgallery');
 assert.equal(m.updateChannel({platform:'android'}),'website');
 assert.equal(m.updateChannel({platform:'android',updateChannel:'play-store'}),'unavailable');
 assert.equal(m.updateChannel(null),'unavailable');
 let checks=0;
 let info={client_id:'test-client-id-1234567890',platform:'harmonyos',automatic:false,lastCheck:0};
 window.cubeofficeServices={getInfo:()=>JSON.stringify(info),request:()=>{checks++;return 'store-check';},takeResult:()=>JSON.stringify({ok:true,data:{channel:'appgallery',available:true}})};
 assert.equal(await m.checkAutomaticStoreUpdate(),false);
 assert.equal(checks,0);
 info.automatic=true;
 info.lastCheck=Date.now();
 assert.equal(await m.checkAutomaticStoreUpdate(),false);
 assert.equal(checks,0);
 info.lastCheck=0;
 assert.equal(await m.checkAutomaticStoreUpdate(),true);
 assert.equal(checks,1);
 info.platform='android';
 assert.equal(await m.checkAutomaticStoreUpdate(),false);
 assert.equal(checks,1);
 console.log('Release validation, async bridge, and store-channel isolation checks passed');
})();
