// Generated by scripts/sync-app-profile.mjs. Do not edit directly.
export const APP_PROFILE = {
	"name": "CubeOffice",
	"packageName": "com.cubexp.office",
	"versionName": "1.3.0",
	"urlScheme": "cubeoffice",
	"documentTemplates": {
		"endpoint": "https://cubexp.com/templates/index.json",
		"formats": [
			"pptx"
		]
	}
} as const;
