// Generated by scripts/sync-app-profile.mjs. Do not edit directly.
export const APP_PROFILE = {
	"name": "CubeOffice",
	"packageName": "com.cubexp.office",
	"versionName": "1.0.0",
	"urlScheme": "cubeoffice"
} as const;
