import { TEXT_EXTENSIONS } from "@cubexp/text/formats";

/** Extensions supported by the registered native formats and import converters. */
export const OPEN_ACCEPT = [
	".ofd",
	...TEXT_EXTENSIONS.map((extension) => `.${extension}`),
	".docx",
	".doc",
	".dot",
	".pptx",
	".ppt",
	".pps",
	".pot",
	".xlsx",
	".xls",
	".xlt",
	".csv",
	".jmp",
	".vsdx",
	".drawio",
	".md",
	".markdown",
	".pdf",
	".png",
	".jpg",
	".jpeg",
	".webp",
	".emf",
	".wmf",
].join(",");
